// front-end/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormInputBarComponent } from '../../components/form-input-bar/form-input-bar.component';
import { LoginRegisterButtonComponent } from "../../components/login-register-button/login-register-button.component";
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormInputBarComponent, LoginRegisterButtonComponent, RouterLink],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {

}

<main class="main-container">
    <aside class="aside-container">
        <img src="/assets/logoDLZ.svg" alt="Logo">
    </aside>

    <section class="section-container">
        <h1 class="main-title">Login</h1>

        <div class="form-container">
            <form action="">
                <app-form-input-bar [type]="'text'" [placeholder]="'Email'"></app-form-input-bar>
                <app-form-input-bar [type]="'password'" [placeholder]="'Senha'"></app-form-input-bar>
            </form>
            <p class="forgot-password"><a href="#">Esqueceu a senha?</a></p>
            <app-login-register-button class="login-register-button" btnText="Entrar"></app-login-register-button>
        </div>

        <p class="register-text">Não tem conta? <a routerLink="/register">Registre-se</a></p>
    </section>
</main>

// front-end/src/pages/Login/Login.jsx
import React from "react";
import { InputField, Button } from '../../components';
import logoDLZ from '../../assets/logoDLZ.svg';
import facebook from '../../assets/facebook.svg';
import google from '../../assets/google.png';
import "./style.css";

export default function Login() {
  return (
    <main className="main">
      <div className="background"></div>
      <aside className="left-aside">
        <img src={logoDLZ} alt="Logo" className="logo" />
      </aside>

      <div className="right-aside">
        <h1 className="title">Login</h1>
        <div className="line-title"></div>
        <form action="" className="form">
          <InputField placeholder="Email" type="email" />
          <InputField placeholder="Senha" type="password" />

          <a href="#" className="forgot-password">Esqueceu sua senha?</a>

          <Button size="large">Login</Button>
        </form>

        <div className="or">
          <div className="line-or"></div>
          <p>ou</p>
          <div className="line-or"></div>
        </div>

        <div className="logins">
          <div className="facebook-login"><img src={facebook} alt="" className="login-image" /></div>
          <div className="google-login"><img src={google} alt="" className="login-image" /></div>
        </div>

        <p className="signin">Não tem uma conta? <a href="#" className="signin-link">Registre-se</a></p>
      </div>
    </main>
  );
}
